### ISSUE TITLE
Initial Review

### ISSUE THREAD

**Issue by dschier-wtd** [while-true-do/ansible-role-httpd#1]
### Type of Report

Review Request

### Actual behaviour

Role had no initial review.

### Expected behaviour

Role must be reviewed and commented.

**Comment by daniel-schier** [comment]
After a day I have done a "self review" with my rubber duck and removed a ton of stuff.

**Comment by daniel-schier** [comment]
mod_ssl needs some work, the defaults are nasty.

https://wiki.mozilla.org/Security/TLS_Configurations

**Comment by daniel-schier** [comment]
working on it... not as trivial as i initally thought.
https://github.com/while-true-do/ansible-role-httpd/tree/init-review

Helpers:
https://mozilla.github.io/server-side-tls/ssl-config-generator/?server=apache-2.4.6&openssl=1.0.2k&hsts=yes&profile=intermediate
https://github.com/mozilla/cipherscan
https://github.com/mozilla/tls-observatory
https://wiki.mozilla.org/Security/TLS_Configurations#Apache
https://www.ssllabs.com/ssltest/
https://github.com/ssllabs/ssllabs-scan/blob/master/ssllabs-api-docs-v3.md

**Comment by daniel-schier** [comment]
Also found something dumb...

```
 - wtd_httpd_mod_ssl_security != "absent"
# must be
- wtd_httpd_mod_security_state != "absent"
```

**Comment by daniel-schier** [comment]
/remind me to finish this in 4 days

**Comment by daniel-schier** [comment]
most of the stuff is done in the branch. will be done end of this week.
